### ISSUE TITLE
Enable MicroStation DGN and AutoCAD DXF drivers.

### ISSUE THREAD

**Issue by lionpham-gis** [kikitte/GDAL4Android#1]
Awesome, 

How can i enable MicroStation DGN, AutoCAD DXF and GeoPDF drivers.

Thank you so much,

**Comment by kikitte** [comment]
You may reading the [gdal building guide](https://gdal.org/development/building_from_source.html), currently this project produce a minimal build, you can enable these drivers by adding `-DOGR_ENABLE_DRIVER_<driver_name>=ON` to the cmake command used for configure gdal in the following section:
https://github.com/kikitte/GDAL4Android/blob/d8086d7855ebf39d2c7cb548606e62bab71fa058/gdal/build_cpp.sh#L91-L111

Please note that some drivers may require extra dependencies(e.g. kml rquires expat), you should build & install them before building gdal, so modification to build_cpp.sh is also needed.

**Comment by lionpham-gis** [comment]
I have enabled DGN and DXF Drivers, but I get compilation error with GeoPDF and PDFium library.
Bạn có thể cập nhật repo này với PDFium library like Expat library.

Many thanks,

**Comment by kikitte** [comment]
Could you attach the error log?

**Comment by yw19841107** [comment]
> Task :gdal:BuildGDALNative FAILED
Execution failed for task ':gdal:BuildGDALNative'.
> A problem occurred starting process 'command 'bash''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
