### ISSUE TITLE
3.7 only 17 Drivers?

### ISSUE THREAD

**Issue by NodeGIS** [kikitte/GDAL4Android#12]
I upgraded to version 3.7.0 and found that there are only 17 drivers available, with PNG, TIFF, etc., missing. Why is this happening? Thank you!

**Comment by kikitte** [comment]
Optional drivers is disabled by default for a small library size: 13.8mb(mini) vs 21.4mb(full)

Just set GDAL_BUILD_OPTIONAL_DRIVERS&OGR_BUILD_OPTIONAL_DRIVERS to ON for a build of all build-in drivers enabled. https://github.com/kikitte/GDAL4Android/blob/6ea9b49229846690c7b908fd34e2c330846f6311/gdal/build_cpp.sh#L142-L143

**Comment by NodeGIS** [comment]
OK， very good！
