### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by yw19841107** [kikitte/GDAL4Android#2]
I downloaded your code and the following error occurred when running it, please help me, thank you

Task :gdal:BuildGDALNative FAILED
Execution failed for task ':gdal:BuildGDALNative'.
A problem occurred starting process 'command 'bash''

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

**Comment by kikitte** [comment]
No enough information provided for your question， please give more( stack trace, bash execution logs, ...), or you can use the prebuild version in the release page.
