### ISSUE TITLE
some error,for help

### ISSUE THREAD

**Issue by RamboMing** [kikitte/GDAL4Android#3]
[log.log](https://github.com/kikitte/GDAL4Android/files/13859322/log.log)
CMake Error at generate_proj_db.cmake:22 (message):
SQLite3 failed
CMake Error at generate_proj_db.cmake:22 (message):
SQLite3 failed

CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find PROJ (missing: PROJ_LIBRARY PROJ_INCLUDE_DIR) (Required is
at least version "6.0")
Call Stack (most recent call first):
/usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
cmake/modules/packages/FindPROJ.cmake:57 (find_package_handle_standard_args)
cmake/helpers/CheckDependentLibraries.cmake:378 (find_package)
gdal.cmake:265 (include)
CMakeLists.txt:246 (include)
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find PROJ (missing: PROJ_LIBRARY PROJ_INCLUDE_DIR) (Required is
at least version "6.0")
Call Stack (most recent call first):
/usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
cmake/modules/packages/FindPROJ.cmake:57 (find_package_handle_standard_args)
cmake/helpers/CheckDependentLibraries.cmake:378 (find_package)
gdal.cmake:265 (include)
CMakeLists.txt:246 (include)

**Comment by kikitte** [comment]
看起来ndk版本有点老，使用r25或者更新的版本看下。

**Comment by RamboMing** [comment]
> 看起来ndk版本有点老，使用r25或者更新的版本看下。

ndk 版本 22，23，24，25，26都试过了，还是同样的问题

**Comment by kikitte** [comment]
我发现你那边日志中的用到的编译器是clang，和我这边的还不一样我这边用的是android-sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang。建议打印检查下下面这几个编译相关变量的输出是何值。https://github.com/kikitte/GDAL4Android/blob/d8086d7855ebf39d2c7cb548606e62bab71fa058/gdal/build_cpp.sh#L163-L173  

我不确定为什么会这样，因为照上面的变量替换来说$CC应该是类似上面x86_64-linux-android21-clang才对，cmake配置GDAL编译的东西应该会从环境变量里读取到上述的配置。可能和环境有关，我这里的环境可以参考下：cmake 3.28.1、bash 5.2.21 系统是ArchLinux。建议升级下cmake版本再尝试以下，Linux编译环境配置多样，会出现的情况很多。

我想对于这个小项目而言，最好的解决办法是考虑能不能把整体编译的逻辑能在用Dockerfile整起来。

**Comment by RamboMing** [comment]
> 我发现你那边日志中的用到的编译器是clang，和我这边的还不一样我这边用的是android-sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang。建议打印检查下下面这几个编译相关变量的输出是何值。
> 
> https://github.com/kikitte/GDAL4Android/blob/d8086d7855ebf39d2c7cb548606e62bab71fa058/gdal/build_cpp.sh#L163-L173
> 
> 我不确定为什么会这样，因为照上面的变量替换来说$CC应该是类似上面x86_64-linux-android21-clang才对，cmake配置GDAL编译的东西应该会从环境变量里读取到上述的配置。可能和环境有关，我这里的环境可以参考下：cmake 3.28.1、bash 5.2.21 系统是ArchLinux。建议升级下cmake版本再尝试以下，Linux编译环境配置多样，会出现的情况很多。
> 
> 我想对于这个小项目而言，最好的解决办法是考虑能不能把整体编译的逻辑能在用Dockerfile整起来。



virtualbox重新安装Ubantu，还是不行，可能是环境的问题；可以帮忙编译armeabi-v7a/arm64-v8a 这两个平台吗

**Comment by kikitte** [comment]
> > 我发现你那边日志中的用到的编译器是clang，和我这边的还不一样我这边用的是android-sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang。建议打印检查下下面这几个编译相关变量的输出是何值。
> > https://github.com/kikitte/GDAL4Android/blob/d8086d7855ebf39d2c7cb548606e62bab71fa058/gdal/build_cpp.sh#L163-L173
> > 
> > 我不确定为什么会这样，因为照上面的变量替换来说$CC应该是类似上面x86_64-linux-android21-clang才对，cmake配置GDAL编译的东西应该会从环境变量里读取到上述的配置。可能和环境有关，我这里的环境可以参考下：cmake 3.28.1、bash 5.2.21 系统是ArchLinux。建议升级下cmake版本再尝试以下，Linux编译环境配置多样，会出现的情况很多。
> > 我想对于这个小项目而言，最好的解决办法是考虑能不能把整体编译的逻辑能在用Dockerfile整起来。
> 
> virtualbox重新安装Ubantu，还是不行，可能是环境的问题；可以帮忙编译armeabi-v7a/arm64-v8a 这两个平台吗

更新了使用docker来编译的说明，就可以避免环境导致的编译问题了。要编译armeabi-v7a平台貌似还有些问题，得在看下。

**Comment by RamboMing** [comment]
使用docker 统一编译环境,确实可行！！！！感谢 kikitte 分享和指导
这里记录几个碰到的问题和解决办法
1.无法下载 expat/sqlite/pro/gdal ，墙的问题，可以在window下翻墙下载成功后，然后拷贝到GDAL4Android/gdal/cpp
2.gradle 下载问题，参照1，拷贝到对应位置
3. docker 环境下，在 /root/GDAL4Android 下执行   ./gradlew :gdal:assembleReleas 提示没有./gradlew 权限
  切换到 /root/GDAL4Android/gdal/ 下执行 gradle :gdal:assembleReleas
