### ISSUE TITLE
我导出shp中文乱码

### ISSUE THREAD

**Issue by lcf001** [kikitte/GDAL4Android#7]
中文属性值都是乱码，网上方法都差不多都不行，要怎么弄啊

**Comment by kikitte** [comment]
请准备一个可复现案例后再重开此问题。

**Comment by lanzhu1993** [comment]
> ndroid工程后再重开此问题

有两个问题，
1、shapefile 编码格式是GBK，加载属性字段是乱码
2、shapefile字段长度是超过10个字符（中文超过3个），写和读都是乱码
